const $=id=>document.getElementById(id);let mode='login',currentChannel='umum',user='Pengguna';
const seed={umum:[['Naya','N','green','09:41','Halo semuanya! 👋 Senang banget akhirnya punya ruang buat ngobrol bareng.'],['Raka','R','purple','09:43','Selamat datang! Di sini kita bisa ngobrol soal game, karya, atau apa pun yang lagi kalian suka.'],['Salsa','S','blue','09:48','Jangan lupa mampir ke kanal pamer-karya ya. Penasaran lihat kreasi kalian ✨']],perkenalan:[['Admin','A','orange','09:30','Yuk kenalan! Ceritakan nama panggilan dan hal yang kamu suka.']],gaming:[['Raka','R','purple','10:02','Lagi ada yang main game apa hari ini? 🎮']],karya:[['Salsa','S','blue','10:10','Tempat berbagi karya, proses kreatif, dan saling kasih masukan dengan baik.']],bantuan:[['Admin','A','orange','09:30','Butuh bantuan? Tulis pertanyaanmu di sini.']]};
let posts=JSON.parse(JSON.stringify(seed));
function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2400)}
function setMode(next){mode=next;const reg=mode==='register';$('authTitle').textContent=reg?'Buat akun RuangKita':'Selamat datang kembali';$('authSubtitle').textContent=reg?'Mulai bergabung dan temukan komunitas yang cocok untukmu.':'Masuk untuk melanjutkan obrolan dan menemukan teman baru.';$('authSubmit').innerHTML=reg?'Buat akun <span>→</span>':'Masuk <span>→</span>';$('authSwitch').firstChild.textContent=reg?'Sudah punya akun? ':'Belum punya akun? ';$('switchMode').textContent=reg?'Masuk':'Daftar';$('authName').classList.toggle('hidden',!reg);$('nameLabel').classList.toggle('hidden',!reg);$('authName').required=reg;$('password').autocomplete=reg?'new-password':'current-password'}
$('switchMode').onclick=()=>setMode(mode==='login'?'register':'login');$('togglePassword').onclick=()=>{const p=$('password');p.type=p.type==='password'?'text':'password';$('togglePassword').textContent=p.type==='password'?'◉':'◎';$('togglePassword').setAttribute('aria-label',p.type==='password'?'Tampilkan kata sandi':'Sembunyikan kata sandi');};
$('authForm').onsubmit=e=>{e.preventDefault();user=mode==='register'?($('authName').value.trim()||'Pengguna'):(($('email').value.split('@')[0]||'Pengguna').replace(/[._-]/g,' '));$('userName').textContent=user;$('authView').classList.add('hidden');$('appView').classList.remove('hidden');$('appView').style.display='grid';renderPosts();toast(`Selamat datang, ${user}!`)};
$('logoutBtn').onclick=()=>{$('appView').classList.add('hidden');$('appView').style.display='';$('authView').classList.remove('hidden');$('password').value=''};
function renderPosts(){const area=$('posts');area.innerHTML='';(posts[currentChannel]||[]).forEach(([name,initial,color,time,message],i)=>{const el=document.createElement('article');el.className='post';const av=document.createElement('div');av.className=`post-avatar ${color}`;av.textContent=initial;const body=document.createElement('div');body.className='post-body';const head=document.createElement('div');head.className='post-head';const b=document.createElement('b');b.textContent=name;const tm=document.createElement('time');tm.textContent=time;head.append(b,tm);const p=document.createElement('p');p.textContent=message;const react=document.createElement('button');react.className='reaction';react.textContent='♡  '+(i===0?3:1);react.onclick=()=>{react.textContent=react.textContent.startsWith('♡')?'♥  '+(i===0?4:2):'♡  '+(i===0?3:1)};body.append(head,p,react);el.append(av,body);area.append(el)})}
function selectChannel(ch){currentChannel=ch;$('channelTitle').textContent=ch;$('messageInput').placeholder=`Kirim pesan ke #${ch}`;document.querySelectorAll('.channel').forEach(b=>b.classList.toggle('active',b.dataset.channel===ch));renderPosts();document.querySelector('.sidebar').classList.remove('open')}
document.querySelectorAll('.channel').forEach(b=>b.onclick=()=>selectChannel(b.dataset.channel));$('messageForm').onsubmit=e=>{e.preventDefault();const value=$('messageInput').value.trim();if(!value)return;posts[currentChannel]??=[];const now=new Date().toLocaleTimeString('id-ID',{hour:'2-digit',minute:'2-digit'});posts[currentChannel].push([user,user[0].toUpperCase(),'blue',now,value]);$('messageInput').value='';renderPosts();$('feed').scrollTop=$('feed').scrollHeight};$('mobileMenu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');$('channelSearch').oninput=e=>{const q=e.target.value.toLowerCase();document.querySelectorAll('.channel').forEach(b=>b.style.display=b.textContent.toLowerCase().includes(q)?'block':'none')};$('addChannel').onclick=()=>{const name=prompt('Nama kanal baru (tanpa #):');if(!name)return;const slug=name.toLowerCase().trim().replace(/\s+/g,'-').replace(/[^a-z0-9-]/g,'');if(!slug||posts[slug])return toast('Nama kanal tidak valid atau sudah ada.');posts[slug]=[];const btn=document.createElement('button');btn.className='channel';btn.dataset.channel=slug;btn.innerHTML=`<span>#</span> ${slug}`;btn.onclick=()=>selectChannel(slug);$('channelList').append(btn);selectChannel(slug);toast('Kanal dibuat (tersimpan selama sesi ini).')};$('newPostBtn').onclick=()=>{$('messageInput').focus();toast('Tulis pesan di kolom bawah untuk memulai postingan.')};$('attachBtn').onclick=()=>toast('Lampiran akan tersedia saat backend ditambahkan.');$('newDm').onclick=()=>toast('Pesan langsung sedang dalam tahap pengembangan.');document.querySelectorAll('.server').forEach((b,i)=>b.onclick=()=>toast(i===0?'Kamu berada di RuangKita.':'Komunitas lain bisa ditambahkan nanti.'));
// Rive initialization. Asset may use different artboard/state-machine names; gracefully fall back to default artboard.
(function initRive(){const canvas=$('teddyCanvas'),loading=$('teddyLoading');if(!window rive||!canvas){loading.textContent='Animasi teddy belum dapat dimuat.';return}try{const teddy=new rive.Rive({src:'assets/auth_teddy.riv',canvas,autoplay:true,fit:rive.Fit.Contain,alignment:rive.Alignment.Center,onLoad:()=>{teddy.resizeDrawingSurfaceToCanvas();loading.style.display='none';},onLoadError:()=>{loading.textContent='Animasi tidak dapat dimuat.'}});window.addEventListener('resize',()=>teddy.resizeDrawingSurfaceToCanvas());$('password').addEventListener('input',()=>{ /* State machine input names depend on the supplied Rive file. */ });}catch(err){loading.textContent='Animasi teddy belum tersedia.'}})();
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
